/**
 * Report model
 *
 * Stores generated reports and their metadata
 * Reports are tenant-scoped and expire after 7 days
 */

import { model, Schema } from "mongoose";

// Report status
export const ReportStatus = {
	PENDING: "PENDING",
	GENERATING: "GENERATING",
	COMPLETED: "COMPLETED",
	FAILED: "FAILED",
} as const;

export type ReportStatusType = (typeof ReportStatus)[keyof typeof ReportStatus];

// Report types
export const ReportType = {
	PATIENT_REGISTRATION: "patient-registration",
	PATIENT_DEMOGRAPHICS: "patient-demographics",
	APPOINTMENT_SUMMARY: "appointment-summary",
	DOCTOR_PERFORMANCE: "doctor-performance",
	PRESCRIPTION_SUMMARY: "prescription-summary",
	MEDICINE_USAGE: "medicine-usage",
	DEPARTMENT_UTILIZATION: "department-utilization",
	STAFF_SUMMARY: "staff-summary",
} as const;

export type ReportTypeType = (typeof ReportType)[keyof typeof ReportType];

// Report formats
export const ReportFormat = {
	JSON: "json",
	CSV: "csv",
	PDF: "pdf",
	XLSX: "xlsx",
} as const;

export type ReportFormatType = (typeof ReportFormat)[keyof typeof ReportFormat];

// Report categories
export const ReportCategory = {
	PATIENT: "PATIENT",
	APPOINTMENT: "APPOINTMENT",
	PRESCRIPTION: "PRESCRIPTION",
	OPERATIONAL: "OPERATIONAL",
	FINANCIAL: "FINANCIAL",
	COMPLIANCE: "COMPLIANCE",
} as const;

export type ReportCategoryType =
	(typeof ReportCategory)[keyof typeof ReportCategory];

// Generated by sub-schema
const generatedBySchema = new Schema(
	{
		id: { type: String, required: true },
		name: { type: String, required: true },
	},
	{ _id: false },
);

// Report schema
const reportSchema = new Schema(
	{
		_id: { type: String },
		tenantId: { type: String, ref: "Organization", required: true },
		reportType: {
			type: String,
			enum: Object.values(ReportType),
			required: true,
		},
		category: {
			type: String,
			enum: Object.values(ReportCategory),
			required: true,
		},
		status: {
			type: String,
			enum: Object.values(ReportStatus),
			default: ReportStatus.PENDING,
		},
		format: {
			type: String,
			enum: Object.values(ReportFormat),
			default: ReportFormat.JSON,
		},
		parameters: { type: Schema.Types.Mixed, required: true },
		data: { type: Schema.Types.Mixed },
		summary: { type: Schema.Types.Mixed },
		generatedBy: { type: generatedBySchema, required: true },
		generatedAt: { type: Date },
		expiresAt: { type: Date },
		errorMessage: { type: String },
	},
	{
		collection: "report",
		timestamps: true,
	},
);

// Indexes: tenant first, then query fields
reportSchema.index({ tenantId: 1, createdAt: -1 });
reportSchema.index({ tenantId: 1, generatedAt: -1 });
reportSchema.index({ tenantId: 1, reportType: 1, status: 1 });
reportSchema.index({ tenantId: 1, "generatedBy.id": 1 });
reportSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 }); // TTL index

export const Report = model("Report", reportSchema);
