import { createFileRoute, Link, redirect } from "@tanstack/react-router";
import {
	type ColumnDef,
	type ColumnFiltersState,
	flexRender,
	getCoreRowModel,
	getFilteredRowModel,
	getPaginationRowModel,
	getSortedRowModel,
	type SortingState,
	useReactTable,
	type VisibilityState,
} from "@tanstack/react-table";
import {
	ArrowUpDown,
	BarChart3,
	Building2,
	Calendar,
	ChevronLeft,
	ChevronRight,
	ChevronsLeft,
	ChevronsRight,
	Download,
	FileBarChart,
	FileText,
	Loader2,
	Pill,
	Users,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { ApiError } from "@/hooks/use-reports";
import {
	type AvailableReport,
	type ReportHistoryItem,
	type ReportStatus,
	useReportHistory,
	useReportTypes,
} from "@/hooks/use-reports";
import { authClient } from "@/lib/auth-client";

export const Route = createFileRoute("/dashboard/reports/")({
	component: ReportsPage,
	beforeLoad: async () => {
		if (!authClient.isAuthenticated()) {
			throw redirect({ to: "/login" });
		}
	},
});

const STATUS_OPTIONS: { value: ReportStatus | "ALL"; label: string }[] = [
	{ value: "ALL", label: "All Statuses" },
	{ value: "PENDING", label: "Pending" },
	{ value: "GENERATING", label: "Generating" },
	{ value: "COMPLETED", label: "Completed" },
	{ value: "FAILED", label: "Failed" },
];

function getStatusBadgeVariant(
	status: ReportStatus,
): "default" | "secondary" | "destructive" | "outline" {
	switch (status) {
		case "COMPLETED":
			return "default";
		case "GENERATING":
			return "secondary";
		case "FAILED":
			return "destructive";
		case "PENDING":
		default:
			return "outline";
	}
}

function getCategoryIcon(category: string) {
	switch (category) {
		case "PATIENT":
			return <Users className="h-5 w-5" />;
		case "APPOINTMENT":
			return <Calendar className="h-5 w-5" />;
		case "PRESCRIPTION":
			return <Pill className="h-5 w-5" />;
		case "OPERATIONAL":
			return <Building2 className="h-5 w-5" />;
		default:
			return <FileBarChart className="h-5 w-5" />;
	}
}

function ReportsPage() {
	const [page, setPage] = useState(1);
	const [statusFilter, setStatusFilter] = useState<string>("");
	const [reportTypeFilter, setReportTypeFilter] = useState<string>("");
	const [dateFilter, setDateFilter] = useState<string>("");
	const [sorting, setSorting] = useState<SortingState>([]);
	const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
	const [columnVisibility, setColumnVisibility] = useState<VisibilityState>({});
	const [rowSelection, setRowSelection] = useState({});

	const { data: reportTypesData, isLoading: reportTypesLoading } =
		useReportTypes();
	const { data: historyData, isLoading: historyLoading } = useReportHistory({
		page,
		limit: 10,
		reportType: reportTypeFilter || undefined,
		startDate: dateFilter || undefined,
	});

	const formatDate = (dateString: string) => {
		return new Date(dateString).toLocaleDateString("en-US", {
			year: "numeric",
			month: "short",
			day: "numeric",
			hour: "2-digit",
			minute: "2-digit",
		});
	};

	const handleDownload = async (report: ReportHistoryItem) => {
		try {
			// For now, just show a toast. In a real implementation, you'd download the file
			toast.success(`Downloading ${report.reportType} report...`);
		} catch (error) {
			const apiError = error as ApiError;
			toast.error(apiError.message || "Failed to download report");
		}
	};

	const columns: ColumnDef<ReportHistoryItem>[] = [
		{
			accessorKey: "reportType",
			header: ({ column }) => (
				<Button
					variant="ghost"
					onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
				>
					Report Type
					<ArrowUpDown className="ml-2 h-4 w-4" />
				</Button>
			),
			cell: ({ row }) => {
				const reportType = row.getValue("reportType") as string;
				return (
					<div className="font-medium">
						{reportType
							.replace(/-/g, " ")
							.replace(/\b\w/g, (l) => l.toUpperCase())}
					</div>
				);
			},
		},
		{
			accessorKey: "format",
			header: "Format",
			cell: ({ row }) => (
				<Badge variant="outline">{row.getValue("format")}</Badge>
			),
		},
		{
			accessorKey: "generatedBy",
			header: "Generated By",
			cell: ({ row }) => {
				const generatedBy = row.original.generatedBy;
				return <div>{generatedBy.name}</div>;
			},
		},
		{
			accessorKey: "generatedAt",
			header: ({ column }) => (
				<Button
					variant="ghost"
					onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
				>
					Generated At
					<ArrowUpDown className="ml-2 h-4 w-4" />
				</Button>
			),
			cell: ({ row }) => (
				<div className="text-muted-foreground">
					{formatDate(row.getValue("generatedAt"))}
				</div>
			),
		},
		{
			accessorKey: "status",
			header: "Status",
			cell: ({ row }) => {
				const status = row.getValue("status") as ReportStatus;
				return <Badge variant={getStatusBadgeVariant(status)}>{status}</Badge>;
			},
		},
		{
			id: "actions",
			enableHiding: false,
			cell: ({ row }) => {
				const report = row.original;
				const canDownload = report.status === "COMPLETED";

				return (
					<div className="flex gap-2">
						{canDownload && (
							<Button
								variant="ghost"
								size="sm"
								onClick={() => handleDownload(report)}
							>
								<Download className="mr-2 h-4 w-4" />
								Download
							</Button>
						)}
						<Button variant="ghost" size="sm" asChild>
							<Link
								to="/dashboard/reports/$id"
								params={{ id: report.reportId }}
							>
								<FileText className="mr-2 h-4 w-4" />
								View
							</Link>
						</Button>
					</div>
				);
			},
		},
	];

	const table = useReactTable({
		data: historyData?.data ?? [],
		columns,
		onSortingChange: setSorting,
		onColumnFiltersChange: setColumnFilters,
		getCoreRowModel: getCoreRowModel(),
		getPaginationRowModel: getPaginationRowModel(),
		getSortedRowModel: getSortedRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		onColumnVisibilityChange: setColumnVisibility,
		onRowSelectionChange: setRowSelection,
		state: {
			sorting,
			columnFilters,
			columnVisibility,
			rowSelection,
		},
		manualPagination: true,
		pageCount: historyData?.pagination.totalPages ?? 0,
	});

	// Group report types by category
	const groupedReportTypes =
		reportTypesData?.reports.reduce(
			(acc, report) => {
				if (!acc[report.category]) {
					acc[report.category] = [];
				}
				acc[report.category].push(report);
				return acc;
			},
			{} as Record<string, AvailableReport[]>,
		) ?? {};

	return (
		<div className="flex flex-col gap-6 p-4 md:gap-8 md:p-6">
			{/* Header */}
			<div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
				<div>
					<h1 className="font-bold text-2xl">Reports</h1>
					<p className="text-muted-foreground">
						Generate and download hospital reports
					</p>
				</div>
				<Button asChild>
					<Link to="/dashboard/reports/generate">
						<FileBarChart className="mr-2 h-4 w-4" />
						Generate Report
					</Link>
				</Button>
			</div>

			<Tabs defaultValue="available" className="space-y-6">
				<TabsList>
					<TabsTrigger value="available">Available Reports</TabsTrigger>
					<TabsTrigger value="history">Report History</TabsTrigger>
				</TabsList>

				{/* Available Reports Tab */}
				<TabsContent value="available" className="space-y-6">
					{reportTypesLoading ? (
						<div className="flex items-center justify-center py-12">
							<Loader2 className="h-8 w-8 animate-spin" />
						</div>
					) : (
						<div className="space-y-8">
							{Object.entries(groupedReportTypes).map(([category, reports]) => (
								<div key={category} className="space-y-4">
									<div className="flex items-center gap-2">
										{getCategoryIcon(category)}
										<h2 className="font-semibold text-lg">
											{category} Reports
										</h2>
									</div>
									<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
										{reports.map((report) => (
											<Card
												key={report.id}
												className="transition-shadow hover:shadow-md"
											>
												<CardHeader>
													<CardTitle className="text-base">
														{report.name}
													</CardTitle>
													<CardDescription>
														{report.description}
													</CardDescription>
												</CardHeader>
												<CardContent>
													<div className="space-y-3">
														<div className="flex flex-wrap gap-1">
															{report.formats.map((format) => (
																<Badge
																	key={format}
																	variant="secondary"
																	className="text-xs"
																>
																	{format.toUpperCase()}
																</Badge>
															))}
														</div>
														<Button
															className="w-full"
															variant="outline"
															asChild
														>
															<Link to="/dashboard/reports/generate">
																<BarChart3 className="mr-2 h-4 w-4" />
																Generate
															</Link>
														</Button>
													</div>
												</CardContent>
											</Card>
										))}
									</div>
								</div>
							))}
						</div>
					)}
				</TabsContent>

				{/* Report History Tab */}
				<TabsContent value="history" className="space-y-6">
					{/* Filters */}
					<div className="flex flex-col gap-4 sm:flex-row sm:items-center">
						<div className="flex gap-2">
							<div className="w-40">
								<Label htmlFor="report-type-filter" className="sr-only">
									Report Type
								</Label>
								<Select
									value={reportTypeFilter}
									onValueChange={(value) => {
										setReportTypeFilter(value);
										setPage(1);
									}}
								>
									<SelectTrigger id="report-type-filter">
										<SelectValue placeholder="All Types" />
									</SelectTrigger>
									<SelectContent>
										<SelectItem value="">All Types</SelectItem>
										{reportTypesData?.reports.map((report) => (
											<SelectItem key={report.id} value={report.id}>
												{report.name}
											</SelectItem>
										))}
									</SelectContent>
								</Select>
							</div>
							<div className="w-40">
								<Label htmlFor="status-filter" className="sr-only">
									Status
								</Label>
								<Select
									value={statusFilter}
									onValueChange={(value) => {
										setStatusFilter(value);
										setPage(1);
									}}
								>
									<SelectTrigger id="status-filter">
										<SelectValue placeholder="All Statuses" />
									</SelectTrigger>
									<SelectContent>
										{STATUS_OPTIONS.map((option) => (
											<SelectItem key={option.value} value={option.value}>
												{option.label}
											</SelectItem>
										))}
									</SelectContent>
								</Select>
							</div>
							<div className="w-40">
								<Label htmlFor="date-filter" className="sr-only">
									Date
								</Label>
								<div className="relative">
									<Calendar className="-translate-y-1/2 absolute top-1/2 left-3 h-4 w-4 text-muted-foreground" />
									<Input
										id="date-filter"
										type="date"
										value={dateFilter}
										onChange={(e) => {
											setDateFilter(e.target.value);
											setPage(1);
										}}
										className="pl-9"
									/>
								</div>
							</div>
							{(reportTypeFilter || statusFilter || dateFilter) && (
								<Button
									variant="ghost"
									onClick={() => {
										setReportTypeFilter("");
										setStatusFilter("");
										setDateFilter("");
										setPage(1);
									}}
								>
									Clear
								</Button>
							)}
						</div>
					</div>

					{/* Table */}
					<div className="rounded-md border">
						<Table>
							<TableHeader>
								{table.getHeaderGroups().map((headerGroup) => (
									<TableRow key={headerGroup.id}>
										{headerGroup.headers.map((header) => (
											<TableHead key={header.id}>
												{header.isPlaceholder
													? null
													: flexRender(
															header.column.columnDef.header,
															header.getContext(),
														)}
											</TableHead>
										))}
									</TableRow>
								))}
							</TableHeader>
							<TableBody>
								{historyLoading ? (
									<TableRow>
										<TableCell
											colSpan={columns.length}
											className="h-24 text-center"
										>
											<Loader2 className="mx-auto h-6 w-6 animate-spin" />
										</TableCell>
									</TableRow>
								) : table.getRowModel().rows?.length ? (
									table.getRowModel().rows.map((row) => (
										<TableRow
											key={row.id}
											data-state={row.getIsSelected() && "selected"}
										>
											{row.getVisibleCells().map((cell) => (
												<TableCell key={cell.id}>
													{flexRender(
														cell.column.columnDef.cell,
														cell.getContext(),
													)}
												</TableCell>
											))}
										</TableRow>
									))
								) : (
									<TableRow>
										<TableCell
											colSpan={columns.length}
											className="h-24 text-center"
										>
											No reports found.
										</TableCell>
									</TableRow>
								)}
							</TableBody>
						</Table>
					</div>

					{/* Pagination */}
					{historyData && (
						<div className="flex items-center justify-between px-2">
							<div className="text-muted-foreground text-sm">
								Showing {historyData.data.length} of{" "}
								{historyData.pagination.total} reports
							</div>
							<div className="flex items-center gap-2">
								<Button
									variant="outline"
									size="icon"
									onClick={() => setPage(1)}
									disabled={page === 1}
								>
									<ChevronsLeft className="h-4 w-4" />
								</Button>
								<Button
									variant="outline"
									size="icon"
									onClick={() => setPage((p) => Math.max(1, p - 1))}
									disabled={page === 1}
								>
									<ChevronLeft className="h-4 w-4" />
								</Button>
								<span className="text-sm">
									Page {page} of {historyData.pagination.totalPages}
								</span>
								<Button
									variant="outline"
									size="icon"
									onClick={() =>
										setPage((p) =>
											Math.min(historyData.pagination.totalPages, p + 1),
										)
									}
									disabled={page === historyData.pagination.totalPages}
								>
									<ChevronRight className="h-4 w-4" />
								</Button>
								<Button
									variant="outline"
									size="icon"
									onClick={() => setPage(historyData.pagination.totalPages)}
									disabled={page === historyData.pagination.totalPages}
								>
									<ChevronsRight className="h-4 w-4" />
								</Button>
							</div>
						</div>
					)}
				</TabsContent>
			</Tabs>
		</div>
	);
}
