/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyHospitalRouteImport } from './routes/verify-hospital'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterHospitalRouteImport } from './routes/register-hospital'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardVitalsIndexRouteImport } from './routes/dashboard/vitals/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardPrescriptionsIndexRouteImport } from './routes/dashboard/prescriptions/index'
import { Route as DashboardPatientsIndexRouteImport } from './routes/dashboard/patients/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/dashboard/inventory/index'
import { Route as DashboardDoctorsIndexRouteImport } from './routes/dashboard/doctors/index'
import { Route as DashboardDispensingIndexRouteImport } from './routes/dashboard/dispensing/index'
import { Route as DashboardDepartmentsIndexRouteImport } from './routes/dashboard/departments/index'
import { Route as DashboardAppointmentsIndexRouteImport } from './routes/dashboard/appointments/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardVitalsRecordRouteImport } from './routes/dashboard/vitals/record'
import { Route as DashboardVitalsHistoryRouteImport } from './routes/dashboard/vitals/history'
import { Route as DashboardVitalsIdRouteImport } from './routes/dashboard/vitals/$id'
import { Route as DashboardStaffRolesRouteImport } from './routes/dashboard/staff/roles'
import { Route as DashboardStaffAddRouteImport } from './routes/dashboard/staff/add'
import { Route as DashboardStaffIdRouteImport } from './routes/dashboard/staff/$id'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsPrivacyRouteImport } from './routes/dashboard/settings/privacy'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsGeneralRouteImport } from './routes/dashboard/settings/general'
import { Route as DashboardSettingsDataExportRouteImport } from './routes/dashboard/settings/data-export'
import { Route as DashboardSettingsDataDeletionRouteImport } from './routes/dashboard/settings/data-deletion'
import { Route as DashboardReportsRevenueRouteImport } from './routes/dashboard/reports/revenue'
import { Route as DashboardReportsPatientsRouteImport } from './routes/dashboard/reports/patients'
import { Route as DashboardReportsGenerateRouteImport } from './routes/dashboard/reports/generate'
import { Route as DashboardReportsAppointmentsRouteImport } from './routes/dashboard/reports/appointments'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard/reports/$id'
import { Route as DashboardPrescriptionsCreateRouteImport } from './routes/dashboard/prescriptions/create'
import { Route as DashboardPrescriptionsIdRouteImport } from './routes/dashboard/prescriptions/$id'
import { Route as DashboardPatientsRegisterRouteImport } from './routes/dashboard/patients/register'
import { Route as DashboardPatientsOpdQueueRouteImport } from './routes/dashboard/patients/opd-queue'
import { Route as DashboardPatientsIdRouteImport } from './routes/dashboard/patients/$id'
import { Route as DashboardInventoryTransactionsRouteImport } from './routes/dashboard/inventory/transactions'
import { Route as DashboardInventoryMedicinesRouteImport } from './routes/dashboard/inventory/medicines'
import { Route as DashboardInventoryExpiringRouteImport } from './routes/dashboard/inventory/expiring'
import { Route as DashboardInventoryIdRouteImport } from './routes/dashboard/inventory/$id'
import { Route as DashboardDoctorsAvailabilityRouteImport } from './routes/dashboard/doctors/availability'
import { Route as DashboardDispensingHistoryRouteImport } from './routes/dashboard/dispensing/history'
import { Route as DashboardDispensingIdRouteImport } from './routes/dashboard/dispensing/$id'
import { Route as DashboardDepartmentsAddRouteImport } from './routes/dashboard/departments/add'
import { Route as DashboardDepartmentsIdRouteImport } from './routes/dashboard/departments/$id'
import { Route as DashboardAppointmentsScheduleRouteImport } from './routes/dashboard/appointments/schedule'
import { Route as DashboardAppointmentsCalendarRouteImport } from './routes/dashboard/appointments/calendar'
import { Route as DashboardAppointmentsIdRouteImport } from './routes/dashboard/appointments/$id'
import { Route as DashboardAdminSecurityRouteImport } from './routes/dashboard/admin/security'
import { Route as DashboardAdminComplianceRouteImport } from './routes/dashboard/admin/compliance'
import { Route as DashboardPrescriptionsTemplatesIndexRouteImport } from './routes/dashboard/prescriptions/templates/index'
import { Route as DashboardAdminSecurityIndexRouteImport } from './routes/dashboard/admin/security/index'
import { Route as DashboardPrescriptionsTemplatesCreateRouteImport } from './routes/dashboard/prescriptions/templates/create'
import { Route as DashboardPrescriptionsTemplatesIdRouteImport } from './routes/dashboard/prescriptions/templates/$id'
import { Route as DashboardAdminSecurityKeysRouteImport } from './routes/dashboard/admin/security/keys'
import { Route as DashboardAdminSecurityEventsRouteImport } from './routes/dashboard/admin/security/events'

const VerifyHospitalRoute = VerifyHospitalRouteImport.update({
  id: '/verify-hospital',
  path: '/verify-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHospitalRoute = RegisterHospitalRouteImport.update({
  id: '/register-hospital',
  path: '/register-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVitalsIndexRoute = DashboardVitalsIndexRouteImport.update({
  id: '/vitals/',
  path: '/vitals/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsIndexRoute =
  DashboardPrescriptionsIndexRouteImport.update({
    id: '/prescriptions/',
    path: '/prescriptions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsIndexRoute = DashboardDoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDispensingIndexRoute =
  DashboardDispensingIndexRouteImport.update({
    id: '/dispensing/',
    path: '/dispensing/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDepartmentsIndexRoute =
  DashboardDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardVitalsRecordRoute = DashboardVitalsRecordRouteImport.update({
  id: '/vitals/record',
  path: '/vitals/record',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVitalsHistoryRoute = DashboardVitalsHistoryRouteImport.update({
  id: '/vitals/history',
  path: '/vitals/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVitalsIdRoute = DashboardVitalsIdRouteImport.update({
  id: '/vitals/$id',
  path: '/vitals/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffRolesRoute = DashboardStaffRolesRouteImport.update({
  id: '/staff/roles',
  path: '/staff/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffAddRoute = DashboardStaffAddRouteImport.update({
  id: '/staff/add',
  path: '/staff/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIdRoute = DashboardStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsPrivacyRoute =
  DashboardSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsDataExportRoute =
  DashboardSettingsDataExportRouteImport.update({
    id: '/data-export',
    path: '/data-export',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsDataDeletionRoute =
  DashboardSettingsDataDeletionRouteImport.update({
    id: '/data-deletion',
    path: '/data-deletion',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardReportsRevenueRoute = DashboardReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsPatientsRoute =
  DashboardReportsPatientsRouteImport.update({
    id: '/reports/patients',
    path: '/reports/patients',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsGenerateRoute =
  DashboardReportsGenerateRouteImport.update({
    id: '/reports/generate',
    path: '/reports/generate',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsAppointmentsRoute =
  DashboardReportsAppointmentsRouteImport.update({
    id: '/reports/appointments',
    path: '/reports/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsCreateRoute =
  DashboardPrescriptionsCreateRouteImport.update({
    id: '/prescriptions/create',
    path: '/prescriptions/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPrescriptionsIdRoute =
  DashboardPrescriptionsIdRouteImport.update({
    id: '/prescriptions/$id',
    path: '/prescriptions/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsRegisterRoute =
  DashboardPatientsRegisterRouteImport.update({
    id: '/patients/register',
    path: '/patients/register',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsOpdQueueRoute =
  DashboardPatientsOpdQueueRouteImport.update({
    id: '/patients/opd-queue',
    path: '/patients/opd-queue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsIdRoute = DashboardPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryTransactionsRoute =
  DashboardInventoryTransactionsRouteImport.update({
    id: '/inventory/transactions',
    path: '/inventory/transactions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryMedicinesRoute =
  DashboardInventoryMedicinesRouteImport.update({
    id: '/inventory/medicines',
    path: '/inventory/medicines',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryExpiringRoute =
  DashboardInventoryExpiringRouteImport.update({
    id: '/inventory/expiring',
    path: '/inventory/expiring',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryIdRoute = DashboardInventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsAvailabilityRoute =
  DashboardDoctorsAvailabilityRouteImport.update({
    id: '/doctors/availability',
    path: '/doctors/availability',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDispensingHistoryRoute =
  DashboardDispensingHistoryRouteImport.update({
    id: '/dispensing/history',
    path: '/dispensing/history',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDispensingIdRoute = DashboardDispensingIdRouteImport.update({
  id: '/dispensing/$id',
  path: '/dispensing/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepartmentsAddRoute = DashboardDepartmentsAddRouteImport.update({
  id: '/departments/add',
  path: '/departments/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepartmentsIdRoute = DashboardDepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsScheduleRoute =
  DashboardAppointmentsScheduleRouteImport.update({
    id: '/appointments/schedule',
    path: '/appointments/schedule',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsCalendarRoute =
  DashboardAppointmentsCalendarRouteImport.update({
    id: '/appointments/calendar',
    path: '/appointments/calendar',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsIdRoute = DashboardAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSecurityRoute = DashboardAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminComplianceRoute =
  DashboardAdminComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardPrescriptionsTemplatesIndexRoute =
  DashboardPrescriptionsTemplatesIndexRouteImport.update({
    id: '/prescriptions/templates/',
    path: '/prescriptions/templates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSecurityIndexRoute =
  DashboardAdminSecurityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdminSecurityRoute,
  } as any)
const DashboardPrescriptionsTemplatesCreateRoute =
  DashboardPrescriptionsTemplatesCreateRouteImport.update({
    id: '/prescriptions/templates/create',
    path: '/prescriptions/templates/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPrescriptionsTemplatesIdRoute =
  DashboardPrescriptionsTemplatesIdRouteImport.update({
    id: '/prescriptions/templates/$id',
    path: '/prescriptions/templates/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSecurityKeysRoute =
  DashboardAdminSecurityKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => DashboardAdminSecurityRoute,
  } as any)
const DashboardAdminSecurityEventsRoute =
  DashboardAdminSecurityEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardAdminSecurityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/compliance': typeof DashboardAdminComplianceRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRouteWithChildren
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/calendar': typeof DashboardAppointmentsCalendarRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/departments/$id': typeof DashboardDepartmentsIdRoute
  '/dashboard/departments/add': typeof DashboardDepartmentsAddRoute
  '/dashboard/dispensing/$id': typeof DashboardDispensingIdRoute
  '/dashboard/dispensing/history': typeof DashboardDispensingHistoryRoute
  '/dashboard/doctors/availability': typeof DashboardDoctorsAvailabilityRoute
  '/dashboard/inventory/$id': typeof DashboardInventoryIdRoute
  '/dashboard/inventory/expiring': typeof DashboardInventoryExpiringRoute
  '/dashboard/inventory/medicines': typeof DashboardInventoryMedicinesRoute
  '/dashboard/inventory/transactions': typeof DashboardInventoryTransactionsRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/reports/appointments': typeof DashboardReportsAppointmentsRoute
  '/dashboard/reports/generate': typeof DashboardReportsGenerateRoute
  '/dashboard/reports/patients': typeof DashboardReportsPatientsRoute
  '/dashboard/reports/revenue': typeof DashboardReportsRevenueRoute
  '/dashboard/settings/data-deletion': typeof DashboardSettingsDataDeletionRoute
  '/dashboard/settings/data-export': typeof DashboardSettingsDataExportRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff/add': typeof DashboardStaffAddRoute
  '/dashboard/staff/roles': typeof DashboardStaffRolesRoute
  '/dashboard/vitals/$id': typeof DashboardVitalsIdRoute
  '/dashboard/vitals/history': typeof DashboardVitalsHistoryRoute
  '/dashboard/vitals/record': typeof DashboardVitalsRecordRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/departments': typeof DashboardDepartmentsIndexRoute
  '/dashboard/dispensing': typeof DashboardDispensingIndexRoute
  '/dashboard/doctors': typeof DashboardDoctorsIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/vitals': typeof DashboardVitalsIndexRoute
  '/dashboard/admin/security/events': typeof DashboardAdminSecurityEventsRoute
  '/dashboard/admin/security/keys': typeof DashboardAdminSecurityKeysRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/admin/security/': typeof DashboardAdminSecurityIndexRoute
  '/dashboard/prescriptions/templates': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/compliance': typeof DashboardAdminComplianceRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/calendar': typeof DashboardAppointmentsCalendarRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/departments/$id': typeof DashboardDepartmentsIdRoute
  '/dashboard/departments/add': typeof DashboardDepartmentsAddRoute
  '/dashboard/dispensing/$id': typeof DashboardDispensingIdRoute
  '/dashboard/dispensing/history': typeof DashboardDispensingHistoryRoute
  '/dashboard/doctors/availability': typeof DashboardDoctorsAvailabilityRoute
  '/dashboard/inventory/$id': typeof DashboardInventoryIdRoute
  '/dashboard/inventory/expiring': typeof DashboardInventoryExpiringRoute
  '/dashboard/inventory/medicines': typeof DashboardInventoryMedicinesRoute
  '/dashboard/inventory/transactions': typeof DashboardInventoryTransactionsRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/reports/appointments': typeof DashboardReportsAppointmentsRoute
  '/dashboard/reports/generate': typeof DashboardReportsGenerateRoute
  '/dashboard/reports/patients': typeof DashboardReportsPatientsRoute
  '/dashboard/reports/revenue': typeof DashboardReportsRevenueRoute
  '/dashboard/settings/data-deletion': typeof DashboardSettingsDataDeletionRoute
  '/dashboard/settings/data-export': typeof DashboardSettingsDataExportRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff/add': typeof DashboardStaffAddRoute
  '/dashboard/staff/roles': typeof DashboardStaffRolesRoute
  '/dashboard/vitals/$id': typeof DashboardVitalsIdRoute
  '/dashboard/vitals/history': typeof DashboardVitalsHistoryRoute
  '/dashboard/vitals/record': typeof DashboardVitalsRecordRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/departments': typeof DashboardDepartmentsIndexRoute
  '/dashboard/dispensing': typeof DashboardDispensingIndexRoute
  '/dashboard/doctors': typeof DashboardDoctorsIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/vitals': typeof DashboardVitalsIndexRoute
  '/dashboard/admin/security/events': typeof DashboardAdminSecurityEventsRoute
  '/dashboard/admin/security/keys': typeof DashboardAdminSecurityKeysRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityIndexRoute
  '/dashboard/prescriptions/templates': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/compliance': typeof DashboardAdminComplianceRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRouteWithChildren
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/calendar': typeof DashboardAppointmentsCalendarRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/departments/$id': typeof DashboardDepartmentsIdRoute
  '/dashboard/departments/add': typeof DashboardDepartmentsAddRoute
  '/dashboard/dispensing/$id': typeof DashboardDispensingIdRoute
  '/dashboard/dispensing/history': typeof DashboardDispensingHistoryRoute
  '/dashboard/doctors/availability': typeof DashboardDoctorsAvailabilityRoute
  '/dashboard/inventory/$id': typeof DashboardInventoryIdRoute
  '/dashboard/inventory/expiring': typeof DashboardInventoryExpiringRoute
  '/dashboard/inventory/medicines': typeof DashboardInventoryMedicinesRoute
  '/dashboard/inventory/transactions': typeof DashboardInventoryTransactionsRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/reports/appointments': typeof DashboardReportsAppointmentsRoute
  '/dashboard/reports/generate': typeof DashboardReportsGenerateRoute
  '/dashboard/reports/patients': typeof DashboardReportsPatientsRoute
  '/dashboard/reports/revenue': typeof DashboardReportsRevenueRoute
  '/dashboard/settings/data-deletion': typeof DashboardSettingsDataDeletionRoute
  '/dashboard/settings/data-export': typeof DashboardSettingsDataExportRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff/add': typeof DashboardStaffAddRoute
  '/dashboard/staff/roles': typeof DashboardStaffRolesRoute
  '/dashboard/vitals/$id': typeof DashboardVitalsIdRoute
  '/dashboard/vitals/history': typeof DashboardVitalsHistoryRoute
  '/dashboard/vitals/record': typeof DashboardVitalsRecordRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
  '/dashboard/dispensing/': typeof DashboardDispensingIndexRoute
  '/dashboard/doctors/': typeof DashboardDoctorsIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions/': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/vitals/': typeof DashboardVitalsIndexRoute
  '/dashboard/admin/security/events': typeof DashboardAdminSecurityEventsRoute
  '/dashboard/admin/security/keys': typeof DashboardAdminSecurityKeysRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/admin/security/': typeof DashboardAdminSecurityIndexRoute
  '/dashboard/prescriptions/templates/': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/compliance'
    | '/dashboard/admin/security'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/calendar'
    | '/dashboard/appointments/schedule'
    | '/dashboard/departments/$id'
    | '/dashboard/departments/add'
    | '/dashboard/dispensing/$id'
    | '/dashboard/dispensing/history'
    | '/dashboard/doctors/availability'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/expiring'
    | '/dashboard/inventory/medicines'
    | '/dashboard/inventory/transactions'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/appointments'
    | '/dashboard/reports/generate'
    | '/dashboard/reports/patients'
    | '/dashboard/reports/revenue'
    | '/dashboard/settings/data-deletion'
    | '/dashboard/settings/data-export'
    | '/dashboard/settings/general'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/privacy'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/staff/$id'
    | '/dashboard/staff/add'
    | '/dashboard/staff/roles'
    | '/dashboard/vitals/$id'
    | '/dashboard/vitals/history'
    | '/dashboard/vitals/record'
    | '/dashboard/admin/'
    | '/dashboard/appointments'
    | '/dashboard/departments'
    | '/dashboard/dispensing'
    | '/dashboard/doctors'
    | '/dashboard/inventory'
    | '/dashboard/patients'
    | '/dashboard/prescriptions'
    | '/dashboard/reports'
    | '/dashboard/settings/'
    | '/dashboard/staff'
    | '/dashboard/vitals'
    | '/dashboard/admin/security/events'
    | '/dashboard/admin/security/keys'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/admin/security/'
    | '/dashboard/prescriptions/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard'
    | '/dashboard/admin/compliance'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/calendar'
    | '/dashboard/appointments/schedule'
    | '/dashboard/departments/$id'
    | '/dashboard/departments/add'
    | '/dashboard/dispensing/$id'
    | '/dashboard/dispensing/history'
    | '/dashboard/doctors/availability'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/expiring'
    | '/dashboard/inventory/medicines'
    | '/dashboard/inventory/transactions'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/appointments'
    | '/dashboard/reports/generate'
    | '/dashboard/reports/patients'
    | '/dashboard/reports/revenue'
    | '/dashboard/settings/data-deletion'
    | '/dashboard/settings/data-export'
    | '/dashboard/settings/general'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/privacy'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/staff/$id'
    | '/dashboard/staff/add'
    | '/dashboard/staff/roles'
    | '/dashboard/vitals/$id'
    | '/dashboard/vitals/history'
    | '/dashboard/vitals/record'
    | '/dashboard/admin'
    | '/dashboard/appointments'
    | '/dashboard/departments'
    | '/dashboard/dispensing'
    | '/dashboard/doctors'
    | '/dashboard/inventory'
    | '/dashboard/patients'
    | '/dashboard/prescriptions'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/vitals'
    | '/dashboard/admin/security/events'
    | '/dashboard/admin/security/keys'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/admin/security'
    | '/dashboard/prescriptions/templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/compliance'
    | '/dashboard/admin/security'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/calendar'
    | '/dashboard/appointments/schedule'
    | '/dashboard/departments/$id'
    | '/dashboard/departments/add'
    | '/dashboard/dispensing/$id'
    | '/dashboard/dispensing/history'
    | '/dashboard/doctors/availability'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/expiring'
    | '/dashboard/inventory/medicines'
    | '/dashboard/inventory/transactions'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/appointments'
    | '/dashboard/reports/generate'
    | '/dashboard/reports/patients'
    | '/dashboard/reports/revenue'
    | '/dashboard/settings/data-deletion'
    | '/dashboard/settings/data-export'
    | '/dashboard/settings/general'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/privacy'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/staff/$id'
    | '/dashboard/staff/add'
    | '/dashboard/staff/roles'
    | '/dashboard/vitals/$id'
    | '/dashboard/vitals/history'
    | '/dashboard/vitals/record'
    | '/dashboard/admin/'
    | '/dashboard/appointments/'
    | '/dashboard/departments/'
    | '/dashboard/dispensing/'
    | '/dashboard/doctors/'
    | '/dashboard/inventory/'
    | '/dashboard/patients/'
    | '/dashboard/prescriptions/'
    | '/dashboard/reports/'
    | '/dashboard/settings/'
    | '/dashboard/staff/'
    | '/dashboard/vitals/'
    | '/dashboard/admin/security/events'
    | '/dashboard/admin/security/keys'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/admin/security/'
    | '/dashboard/prescriptions/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterHospitalRoute: typeof RegisterHospitalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  VerifyHospitalRoute: typeof VerifyHospitalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-hospital': {
      id: '/verify-hospital'
      path: '/verify-hospital'
      fullPath: '/verify-hospital'
      preLoaderRoute: typeof VerifyHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-hospital': {
      id: '/register-hospital'
      path: '/register-hospital'
      fullPath: '/register-hospital'
      preLoaderRoute: typeof RegisterHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitals/': {
      id: '/dashboard/vitals/'
      path: '/vitals'
      fullPath: '/dashboard/vitals'
      preLoaderRoute: typeof DashboardVitalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/': {
      id: '/dashboard/prescriptions/'
      path: '/prescriptions'
      fullPath: '/dashboard/prescriptions'
      preLoaderRoute: typeof DashboardPrescriptionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/': {
      id: '/dashboard/patients/'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors/': {
      id: '/dashboard/doctors/'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dispensing/': {
      id: '/dashboard/dispensing/'
      path: '/dispensing'
      fullPath: '/dashboard/dispensing'
      preLoaderRoute: typeof DashboardDispensingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/departments/': {
      id: '/dashboard/departments/'
      path: '/departments'
      fullPath: '/dashboard/departments'
      preLoaderRoute: typeof DashboardDepartmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/': {
      id: '/dashboard/appointments/'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/vitals/record': {
      id: '/dashboard/vitals/record'
      path: '/vitals/record'
      fullPath: '/dashboard/vitals/record'
      preLoaderRoute: typeof DashboardVitalsRecordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitals/history': {
      id: '/dashboard/vitals/history'
      path: '/vitals/history'
      fullPath: '/dashboard/vitals/history'
      preLoaderRoute: typeof DashboardVitalsHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitals/$id': {
      id: '/dashboard/vitals/$id'
      path: '/vitals/$id'
      fullPath: '/dashboard/vitals/$id'
      preLoaderRoute: typeof DashboardVitalsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/roles': {
      id: '/dashboard/staff/roles'
      path: '/staff/roles'
      fullPath: '/dashboard/staff/roles'
      preLoaderRoute: typeof DashboardStaffRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/add': {
      id: '/dashboard/staff/add'
      path: '/staff/add'
      fullPath: '/dashboard/staff/add'
      preLoaderRoute: typeof DashboardStaffAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/$id': {
      id: '/dashboard/staff/$id'
      path: '/staff/$id'
      fullPath: '/dashboard/staff/$id'
      preLoaderRoute: typeof DashboardStaffIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/privacy': {
      id: '/dashboard/settings/privacy'
      path: '/privacy'
      fullPath: '/dashboard/settings/privacy'
      preLoaderRoute: typeof DashboardSettingsPrivacyRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/general': {
      id: '/dashboard/settings/general'
      path: '/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/data-export': {
      id: '/dashboard/settings/data-export'
      path: '/data-export'
      fullPath: '/dashboard/settings/data-export'
      preLoaderRoute: typeof DashboardSettingsDataExportRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/data-deletion': {
      id: '/dashboard/settings/data-deletion'
      path: '/data-deletion'
      fullPath: '/dashboard/settings/data-deletion'
      preLoaderRoute: typeof DashboardSettingsDataDeletionRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/reports/revenue': {
      id: '/dashboard/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/dashboard/reports/revenue'
      preLoaderRoute: typeof DashboardReportsRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/patients': {
      id: '/dashboard/reports/patients'
      path: '/reports/patients'
      fullPath: '/dashboard/reports/patients'
      preLoaderRoute: typeof DashboardReportsPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/generate': {
      id: '/dashboard/reports/generate'
      path: '/reports/generate'
      fullPath: '/dashboard/reports/generate'
      preLoaderRoute: typeof DashboardReportsGenerateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/appointments': {
      id: '/dashboard/reports/appointments'
      path: '/reports/appointments'
      fullPath: '/dashboard/reports/appointments'
      preLoaderRoute: typeof DashboardReportsAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/create': {
      id: '/dashboard/prescriptions/create'
      path: '/prescriptions/create'
      fullPath: '/dashboard/prescriptions/create'
      preLoaderRoute: typeof DashboardPrescriptionsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/$id': {
      id: '/dashboard/prescriptions/$id'
      path: '/prescriptions/$id'
      fullPath: '/dashboard/prescriptions/$id'
      preLoaderRoute: typeof DashboardPrescriptionsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/register': {
      id: '/dashboard/patients/register'
      path: '/patients/register'
      fullPath: '/dashboard/patients/register'
      preLoaderRoute: typeof DashboardPatientsRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/opd-queue': {
      id: '/dashboard/patients/opd-queue'
      path: '/patients/opd-queue'
      fullPath: '/dashboard/patients/opd-queue'
      preLoaderRoute: typeof DashboardPatientsOpdQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/$id': {
      id: '/dashboard/patients/$id'
      path: '/patients/$id'
      fullPath: '/dashboard/patients/$id'
      preLoaderRoute: typeof DashboardPatientsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/transactions': {
      id: '/dashboard/inventory/transactions'
      path: '/inventory/transactions'
      fullPath: '/dashboard/inventory/transactions'
      preLoaderRoute: typeof DashboardInventoryTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/medicines': {
      id: '/dashboard/inventory/medicines'
      path: '/inventory/medicines'
      fullPath: '/dashboard/inventory/medicines'
      preLoaderRoute: typeof DashboardInventoryMedicinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/expiring': {
      id: '/dashboard/inventory/expiring'
      path: '/inventory/expiring'
      fullPath: '/dashboard/inventory/expiring'
      preLoaderRoute: typeof DashboardInventoryExpiringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/$id': {
      id: '/dashboard/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/dashboard/inventory/$id'
      preLoaderRoute: typeof DashboardInventoryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors/availability': {
      id: '/dashboard/doctors/availability'
      path: '/doctors/availability'
      fullPath: '/dashboard/doctors/availability'
      preLoaderRoute: typeof DashboardDoctorsAvailabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dispensing/history': {
      id: '/dashboard/dispensing/history'
      path: '/dispensing/history'
      fullPath: '/dashboard/dispensing/history'
      preLoaderRoute: typeof DashboardDispensingHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dispensing/$id': {
      id: '/dashboard/dispensing/$id'
      path: '/dispensing/$id'
      fullPath: '/dashboard/dispensing/$id'
      preLoaderRoute: typeof DashboardDispensingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/departments/add': {
      id: '/dashboard/departments/add'
      path: '/departments/add'
      fullPath: '/dashboard/departments/add'
      preLoaderRoute: typeof DashboardDepartmentsAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/departments/$id': {
      id: '/dashboard/departments/$id'
      path: '/departments/$id'
      fullPath: '/dashboard/departments/$id'
      preLoaderRoute: typeof DashboardDepartmentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/schedule': {
      id: '/dashboard/appointments/schedule'
      path: '/appointments/schedule'
      fullPath: '/dashboard/appointments/schedule'
      preLoaderRoute: typeof DashboardAppointmentsScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/calendar': {
      id: '/dashboard/appointments/calendar'
      path: '/appointments/calendar'
      fullPath: '/dashboard/appointments/calendar'
      preLoaderRoute: typeof DashboardAppointmentsCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/$id': {
      id: '/dashboard/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/dashboard/appointments/$id'
      preLoaderRoute: typeof DashboardAppointmentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/security': {
      id: '/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof DashboardAdminSecurityRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/compliance': {
      id: '/dashboard/admin/compliance'
      path: '/compliance'
      fullPath: '/dashboard/admin/compliance'
      preLoaderRoute: typeof DashboardAdminComplianceRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/prescriptions/templates/': {
      id: '/dashboard/prescriptions/templates/'
      path: '/prescriptions/templates'
      fullPath: '/dashboard/prescriptions/templates'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/security/': {
      id: '/dashboard/admin/security/'
      path: '/'
      fullPath: '/dashboard/admin/security/'
      preLoaderRoute: typeof DashboardAdminSecurityIndexRouteImport
      parentRoute: typeof DashboardAdminSecurityRoute
    }
    '/dashboard/prescriptions/templates/create': {
      id: '/dashboard/prescriptions/templates/create'
      path: '/prescriptions/templates/create'
      fullPath: '/dashboard/prescriptions/templates/create'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/templates/$id': {
      id: '/dashboard/prescriptions/templates/$id'
      path: '/prescriptions/templates/$id'
      fullPath: '/dashboard/prescriptions/templates/$id'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/security/keys': {
      id: '/dashboard/admin/security/keys'
      path: '/keys'
      fullPath: '/dashboard/admin/security/keys'
      preLoaderRoute: typeof DashboardAdminSecurityKeysRouteImport
      parentRoute: typeof DashboardAdminSecurityRoute
    }
    '/dashboard/admin/security/events': {
      id: '/dashboard/admin/security/events'
      path: '/events'
      fullPath: '/dashboard/admin/security/events'
      preLoaderRoute: typeof DashboardAdminSecurityEventsRouteImport
      parentRoute: typeof DashboardAdminSecurityRoute
    }
  }
}

interface DashboardAdminSecurityRouteChildren {
  DashboardAdminSecurityEventsRoute: typeof DashboardAdminSecurityEventsRoute
  DashboardAdminSecurityKeysRoute: typeof DashboardAdminSecurityKeysRoute
  DashboardAdminSecurityIndexRoute: typeof DashboardAdminSecurityIndexRoute
}

const DashboardAdminSecurityRouteChildren: DashboardAdminSecurityRouteChildren =
  {
    DashboardAdminSecurityEventsRoute: DashboardAdminSecurityEventsRoute,
    DashboardAdminSecurityKeysRoute: DashboardAdminSecurityKeysRoute,
    DashboardAdminSecurityIndexRoute: DashboardAdminSecurityIndexRoute,
  }

const DashboardAdminSecurityRouteWithChildren =
  DashboardAdminSecurityRoute._addFileChildren(
    DashboardAdminSecurityRouteChildren,
  )

interface DashboardAdminRouteChildren {
  DashboardAdminComplianceRoute: typeof DashboardAdminComplianceRoute
  DashboardAdminSecurityRoute: typeof DashboardAdminSecurityRouteWithChildren
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminComplianceRoute: DashboardAdminComplianceRoute,
  DashboardAdminSecurityRoute: DashboardAdminSecurityRouteWithChildren,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardSettingsRouteChildren {
  DashboardSettingsDataDeletionRoute: typeof DashboardSettingsDataDeletionRoute
  DashboardSettingsDataExportRoute: typeof DashboardSettingsDataExportRoute
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsPrivacyRoute: typeof DashboardSettingsPrivacyRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsDataDeletionRoute: DashboardSettingsDataDeletionRoute,
  DashboardSettingsDataExportRoute: DashboardSettingsDataExportRoute,
  DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsPrivacyRoute: DashboardSettingsPrivacyRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppointmentsIdRoute: typeof DashboardAppointmentsIdRoute
  DashboardAppointmentsCalendarRoute: typeof DashboardAppointmentsCalendarRoute
  DashboardAppointmentsScheduleRoute: typeof DashboardAppointmentsScheduleRoute
  DashboardDepartmentsIdRoute: typeof DashboardDepartmentsIdRoute
  DashboardDepartmentsAddRoute: typeof DashboardDepartmentsAddRoute
  DashboardDispensingIdRoute: typeof DashboardDispensingIdRoute
  DashboardDispensingHistoryRoute: typeof DashboardDispensingHistoryRoute
  DashboardDoctorsAvailabilityRoute: typeof DashboardDoctorsAvailabilityRoute
  DashboardInventoryIdRoute: typeof DashboardInventoryIdRoute
  DashboardInventoryExpiringRoute: typeof DashboardInventoryExpiringRoute
  DashboardInventoryMedicinesRoute: typeof DashboardInventoryMedicinesRoute
  DashboardInventoryTransactionsRoute: typeof DashboardInventoryTransactionsRoute
  DashboardPatientsIdRoute: typeof DashboardPatientsIdRoute
  DashboardPatientsOpdQueueRoute: typeof DashboardPatientsOpdQueueRoute
  DashboardPatientsRegisterRoute: typeof DashboardPatientsRegisterRoute
  DashboardPrescriptionsIdRoute: typeof DashboardPrescriptionsIdRoute
  DashboardPrescriptionsCreateRoute: typeof DashboardPrescriptionsCreateRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
  DashboardReportsAppointmentsRoute: typeof DashboardReportsAppointmentsRoute
  DashboardReportsGenerateRoute: typeof DashboardReportsGenerateRoute
  DashboardReportsPatientsRoute: typeof DashboardReportsPatientsRoute
  DashboardReportsRevenueRoute: typeof DashboardReportsRevenueRoute
  DashboardStaffIdRoute: typeof DashboardStaffIdRoute
  DashboardStaffAddRoute: typeof DashboardStaffAddRoute
  DashboardStaffRolesRoute: typeof DashboardStaffRolesRoute
  DashboardVitalsIdRoute: typeof DashboardVitalsIdRoute
  DashboardVitalsHistoryRoute: typeof DashboardVitalsHistoryRoute
  DashboardVitalsRecordRoute: typeof DashboardVitalsRecordRoute
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute
  DashboardDepartmentsIndexRoute: typeof DashboardDepartmentsIndexRoute
  DashboardDispensingIndexRoute: typeof DashboardDispensingIndexRoute
  DashboardDoctorsIndexRoute: typeof DashboardDoctorsIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute
  DashboardPrescriptionsIndexRoute: typeof DashboardPrescriptionsIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardVitalsIndexRoute: typeof DashboardVitalsIndexRoute
  DashboardPrescriptionsTemplatesIdRoute: typeof DashboardPrescriptionsTemplatesIdRoute
  DashboardPrescriptionsTemplatesCreateRoute: typeof DashboardPrescriptionsTemplatesCreateRoute
  DashboardPrescriptionsTemplatesIndexRoute: typeof DashboardPrescriptionsTemplatesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppointmentsIdRoute: DashboardAppointmentsIdRoute,
  DashboardAppointmentsCalendarRoute: DashboardAppointmentsCalendarRoute,
  DashboardAppointmentsScheduleRoute: DashboardAppointmentsScheduleRoute,
  DashboardDepartmentsIdRoute: DashboardDepartmentsIdRoute,
  DashboardDepartmentsAddRoute: DashboardDepartmentsAddRoute,
  DashboardDispensingIdRoute: DashboardDispensingIdRoute,
  DashboardDispensingHistoryRoute: DashboardDispensingHistoryRoute,
  DashboardDoctorsAvailabilityRoute: DashboardDoctorsAvailabilityRoute,
  DashboardInventoryIdRoute: DashboardInventoryIdRoute,
  DashboardInventoryExpiringRoute: DashboardInventoryExpiringRoute,
  DashboardInventoryMedicinesRoute: DashboardInventoryMedicinesRoute,
  DashboardInventoryTransactionsRoute: DashboardInventoryTransactionsRoute,
  DashboardPatientsIdRoute: DashboardPatientsIdRoute,
  DashboardPatientsOpdQueueRoute: DashboardPatientsOpdQueueRoute,
  DashboardPatientsRegisterRoute: DashboardPatientsRegisterRoute,
  DashboardPrescriptionsIdRoute: DashboardPrescriptionsIdRoute,
  DashboardPrescriptionsCreateRoute: DashboardPrescriptionsCreateRoute,
  DashboardReportsIdRoute: DashboardReportsIdRoute,
  DashboardReportsAppointmentsRoute: DashboardReportsAppointmentsRoute,
  DashboardReportsGenerateRoute: DashboardReportsGenerateRoute,
  DashboardReportsPatientsRoute: DashboardReportsPatientsRoute,
  DashboardReportsRevenueRoute: DashboardReportsRevenueRoute,
  DashboardStaffIdRoute: DashboardStaffIdRoute,
  DashboardStaffAddRoute: DashboardStaffAddRoute,
  DashboardStaffRolesRoute: DashboardStaffRolesRoute,
  DashboardVitalsIdRoute: DashboardVitalsIdRoute,
  DashboardVitalsHistoryRoute: DashboardVitalsHistoryRoute,
  DashboardVitalsRecordRoute: DashboardVitalsRecordRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardDepartmentsIndexRoute: DashboardDepartmentsIndexRoute,
  DashboardDispensingIndexRoute: DashboardDispensingIndexRoute,
  DashboardDoctorsIndexRoute: DashboardDoctorsIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
  DashboardPrescriptionsIndexRoute: DashboardPrescriptionsIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardVitalsIndexRoute: DashboardVitalsIndexRoute,
  DashboardPrescriptionsTemplatesIdRoute:
    DashboardPrescriptionsTemplatesIdRoute,
  DashboardPrescriptionsTemplatesCreateRoute:
    DashboardPrescriptionsTemplatesCreateRoute,
  DashboardPrescriptionsTemplatesIndexRoute:
    DashboardPrescriptionsTemplatesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterHospitalRoute: RegisterHospitalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
  VerifyHospitalRoute: VerifyHospitalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
