/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyHospitalRouteImport } from './routes/verify-hospital'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterHospitalRouteImport } from './routes/register-hospital'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardVitalsIndexRouteImport } from './routes/dashboard/vitals/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardPrescriptionsIndexRouteImport } from './routes/dashboard/prescriptions/index'
import { Route as DashboardPatientsIndexRouteImport } from './routes/dashboard/patients/index'
import { Route as DashboardDispensingIndexRouteImport } from './routes/dashboard/dispensing/index'
import { Route as DashboardAppointmentsIndexRouteImport } from './routes/dashboard/appointments/index'
import { Route as DashboardVitalsRecordRouteImport } from './routes/dashboard/vitals/record'
import { Route as DashboardVitalsHistoryRouteImport } from './routes/dashboard/vitals/history'
import { Route as DashboardVitalsIdRouteImport } from './routes/dashboard/vitals/$id'
import { Route as DashboardStaffRolesRouteImport } from './routes/dashboard/staff/roles'
import { Route as DashboardStaffIdRouteImport } from './routes/dashboard/staff/$id'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsGeneralRouteImport } from './routes/dashboard/settings/general'
import { Route as DashboardPrescriptionsCreateRouteImport } from './routes/dashboard/prescriptions/create'
import { Route as DashboardPrescriptionsIdRouteImport } from './routes/dashboard/prescriptions/$id'
import { Route as DashboardPatientsRegisterRouteImport } from './routes/dashboard/patients/register'
import { Route as DashboardPatientsOpdQueueRouteImport } from './routes/dashboard/patients/opd-queue'
import { Route as DashboardPatientsIdRouteImport } from './routes/dashboard/patients/$id'
import { Route as DashboardDispensingHistoryRouteImport } from './routes/dashboard/dispensing/history'
import { Route as DashboardDispensingIdRouteImport } from './routes/dashboard/dispensing/$id'
import { Route as DashboardAppointmentsScheduleRouteImport } from './routes/dashboard/appointments/schedule'
import { Route as DashboardAppointmentsIdRouteImport } from './routes/dashboard/appointments/$id'
import { Route as DashboardAdminSecurityRouteImport } from './routes/dashboard/admin/security'
import { Route as DashboardPrescriptionsTemplatesIndexRouteImport } from './routes/dashboard/prescriptions/templates/index'
import { Route as DashboardAdminSecurityIndexRouteImport } from './routes/dashboard/admin/security/index'
import { Route as DashboardPrescriptionsTemplatesCreateRouteImport } from './routes/dashboard/prescriptions/templates/create'
import { Route as DashboardPrescriptionsTemplatesIdRouteImport } from './routes/dashboard/prescriptions/templates/$id'
import { Route as DashboardAdminSecurityKeysRouteImport } from './routes/dashboard/admin/security/keys'
import { Route as DashboardAdminSecurityEventsRouteImport } from './routes/dashboard/admin/security/events'

const VerifyHospitalRoute = VerifyHospitalRouteImport.update({
  id: '/verify-hospital',
  path: '/verify-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHospitalRoute = RegisterHospitalRouteImport.update({
  id: '/register-hospital',
  path: '/register-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVitalsIndexRoute = DashboardVitalsIndexRouteImport.update({
  id: '/vitals/',
  path: '/vitals/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardPrescriptionsIndexRoute =
  DashboardPrescriptionsIndexRouteImport.update({
    id: '/prescriptions/',
    path: '/prescriptions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDispensingIndexRoute =
  DashboardDispensingIndexRouteImport.update({
    id: '/dispensing/',
    path: '/dispensing/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardVitalsRecordRoute = DashboardVitalsRecordRouteImport.update({
  id: '/vitals/record',
  path: '/vitals/record',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVitalsHistoryRoute = DashboardVitalsHistoryRouteImport.update({
  id: '/vitals/history',
  path: '/vitals/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVitalsIdRoute = DashboardVitalsIdRouteImport.update({
  id: '/vitals/$id',
  path: '/vitals/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffRolesRoute = DashboardStaffRolesRouteImport.update({
  id: '/staff/roles',
  path: '/staff/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIdRoute = DashboardStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardPrescriptionsCreateRoute =
  DashboardPrescriptionsCreateRouteImport.update({
    id: '/prescriptions/create',
    path: '/prescriptions/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPrescriptionsIdRoute =
  DashboardPrescriptionsIdRouteImport.update({
    id: '/prescriptions/$id',
    path: '/prescriptions/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsRegisterRoute =
  DashboardPatientsRegisterRouteImport.update({
    id: '/patients/register',
    path: '/patients/register',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsOpdQueueRoute =
  DashboardPatientsOpdQueueRouteImport.update({
    id: '/patients/opd-queue',
    path: '/patients/opd-queue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsIdRoute = DashboardPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDispensingHistoryRoute =
  DashboardDispensingHistoryRouteImport.update({
    id: '/dispensing/history',
    path: '/dispensing/history',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDispensingIdRoute = DashboardDispensingIdRouteImport.update({
  id: '/dispensing/$id',
  path: '/dispensing/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsScheduleRoute =
  DashboardAppointmentsScheduleRouteImport.update({
    id: '/appointments/schedule',
    path: '/appointments/schedule',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsIdRoute = DashboardAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSecurityRoute = DashboardAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardPrescriptionsTemplatesIndexRoute =
  DashboardPrescriptionsTemplatesIndexRouteImport.update({
    id: '/prescriptions/templates/',
    path: '/prescriptions/templates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSecurityIndexRoute =
  DashboardAdminSecurityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdminSecurityRoute,
  } as any)
const DashboardPrescriptionsTemplatesCreateRoute =
  DashboardPrescriptionsTemplatesCreateRouteImport.update({
    id: '/prescriptions/templates/create',
    path: '/prescriptions/templates/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPrescriptionsTemplatesIdRoute =
  DashboardPrescriptionsTemplatesIdRouteImport.update({
    id: '/prescriptions/templates/$id',
    path: '/prescriptions/templates/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSecurityKeysRoute =
  DashboardAdminSecurityKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => DashboardAdminSecurityRoute,
  } as any)
const DashboardAdminSecurityEventsRoute =
  DashboardAdminSecurityEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardAdminSecurityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRouteWithChildren
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/dispensing/$id': typeof DashboardDispensingIdRoute
  '/dashboard/dispensing/history': typeof DashboardDispensingHistoryRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff/roles': typeof DashboardStaffRolesRoute
  '/dashboard/vitals/$id': typeof DashboardVitalsIdRoute
  '/dashboard/vitals/history': typeof DashboardVitalsHistoryRoute
  '/dashboard/vitals/record': typeof DashboardVitalsRecordRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/dispensing': typeof DashboardDispensingIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/vitals': typeof DashboardVitalsIndexRoute
  '/dashboard/admin/security/events': typeof DashboardAdminSecurityEventsRoute
  '/dashboard/admin/security/keys': typeof DashboardAdminSecurityKeysRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/admin/security/': typeof DashboardAdminSecurityIndexRoute
  '/dashboard/prescriptions/templates': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/dispensing/$id': typeof DashboardDispensingIdRoute
  '/dashboard/dispensing/history': typeof DashboardDispensingHistoryRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff/roles': typeof DashboardStaffRolesRoute
  '/dashboard/vitals/$id': typeof DashboardVitalsIdRoute
  '/dashboard/vitals/history': typeof DashboardVitalsHistoryRoute
  '/dashboard/vitals/record': typeof DashboardVitalsRecordRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/dispensing': typeof DashboardDispensingIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/vitals': typeof DashboardVitalsIndexRoute
  '/dashboard/admin/security/events': typeof DashboardAdminSecurityEventsRoute
  '/dashboard/admin/security/keys': typeof DashboardAdminSecurityKeysRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityIndexRoute
  '/dashboard/prescriptions/templates': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRouteWithChildren
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/dispensing/$id': typeof DashboardDispensingIdRoute
  '/dashboard/dispensing/history': typeof DashboardDispensingHistoryRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff/roles': typeof DashboardStaffRolesRoute
  '/dashboard/vitals/$id': typeof DashboardVitalsIdRoute
  '/dashboard/vitals/history': typeof DashboardVitalsHistoryRoute
  '/dashboard/vitals/record': typeof DashboardVitalsRecordRoute
  '/dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/dashboard/dispensing/': typeof DashboardDispensingIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions/': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/vitals/': typeof DashboardVitalsIndexRoute
  '/dashboard/admin/security/events': typeof DashboardAdminSecurityEventsRoute
  '/dashboard/admin/security/keys': typeof DashboardAdminSecurityKeysRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/admin/security/': typeof DashboardAdminSecurityIndexRoute
  '/dashboard/prescriptions/templates/': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/security'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/schedule'
    | '/dashboard/dispensing/$id'
    | '/dashboard/dispensing/history'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/settings/general'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/staff/$id'
    | '/dashboard/staff/roles'
    | '/dashboard/vitals/$id'
    | '/dashboard/vitals/history'
    | '/dashboard/vitals/record'
    | '/dashboard/appointments'
    | '/dashboard/dispensing'
    | '/dashboard/patients'
    | '/dashboard/prescriptions'
    | '/dashboard/settings/'
    | '/dashboard/staff'
    | '/dashboard/vitals'
    | '/dashboard/admin/security/events'
    | '/dashboard/admin/security/keys'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/admin/security/'
    | '/dashboard/prescriptions/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/admin'
    | '/dashboard'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/schedule'
    | '/dashboard/dispensing/$id'
    | '/dashboard/dispensing/history'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/settings/general'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/staff/$id'
    | '/dashboard/staff/roles'
    | '/dashboard/vitals/$id'
    | '/dashboard/vitals/history'
    | '/dashboard/vitals/record'
    | '/dashboard/appointments'
    | '/dashboard/dispensing'
    | '/dashboard/patients'
    | '/dashboard/prescriptions'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/vitals'
    | '/dashboard/admin/security/events'
    | '/dashboard/admin/security/keys'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/admin/security'
    | '/dashboard/prescriptions/templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/security'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/schedule'
    | '/dashboard/dispensing/$id'
    | '/dashboard/dispensing/history'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/settings/general'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/staff/$id'
    | '/dashboard/staff/roles'
    | '/dashboard/vitals/$id'
    | '/dashboard/vitals/history'
    | '/dashboard/vitals/record'
    | '/dashboard/appointments/'
    | '/dashboard/dispensing/'
    | '/dashboard/patients/'
    | '/dashboard/prescriptions/'
    | '/dashboard/settings/'
    | '/dashboard/staff/'
    | '/dashboard/vitals/'
    | '/dashboard/admin/security/events'
    | '/dashboard/admin/security/keys'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/admin/security/'
    | '/dashboard/prescriptions/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterHospitalRoute: typeof RegisterHospitalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  VerifyHospitalRoute: typeof VerifyHospitalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-hospital': {
      id: '/verify-hospital'
      path: '/verify-hospital'
      fullPath: '/verify-hospital'
      preLoaderRoute: typeof VerifyHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-hospital': {
      id: '/register-hospital'
      path: '/register-hospital'
      fullPath: '/register-hospital'
      preLoaderRoute: typeof RegisterHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitals/': {
      id: '/dashboard/vitals/'
      path: '/vitals'
      fullPath: '/dashboard/vitals'
      preLoaderRoute: typeof DashboardVitalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/prescriptions/': {
      id: '/dashboard/prescriptions/'
      path: '/prescriptions'
      fullPath: '/dashboard/prescriptions'
      preLoaderRoute: typeof DashboardPrescriptionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/': {
      id: '/dashboard/patients/'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dispensing/': {
      id: '/dashboard/dispensing/'
      path: '/dispensing'
      fullPath: '/dashboard/dispensing'
      preLoaderRoute: typeof DashboardDispensingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/': {
      id: '/dashboard/appointments/'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitals/record': {
      id: '/dashboard/vitals/record'
      path: '/vitals/record'
      fullPath: '/dashboard/vitals/record'
      preLoaderRoute: typeof DashboardVitalsRecordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitals/history': {
      id: '/dashboard/vitals/history'
      path: '/vitals/history'
      fullPath: '/dashboard/vitals/history'
      preLoaderRoute: typeof DashboardVitalsHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitals/$id': {
      id: '/dashboard/vitals/$id'
      path: '/vitals/$id'
      fullPath: '/dashboard/vitals/$id'
      preLoaderRoute: typeof DashboardVitalsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/roles': {
      id: '/dashboard/staff/roles'
      path: '/staff/roles'
      fullPath: '/dashboard/staff/roles'
      preLoaderRoute: typeof DashboardStaffRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/$id': {
      id: '/dashboard/staff/$id'
      path: '/staff/$id'
      fullPath: '/dashboard/staff/$id'
      preLoaderRoute: typeof DashboardStaffIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/general': {
      id: '/dashboard/settings/general'
      path: '/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/prescriptions/create': {
      id: '/dashboard/prescriptions/create'
      path: '/prescriptions/create'
      fullPath: '/dashboard/prescriptions/create'
      preLoaderRoute: typeof DashboardPrescriptionsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/$id': {
      id: '/dashboard/prescriptions/$id'
      path: '/prescriptions/$id'
      fullPath: '/dashboard/prescriptions/$id'
      preLoaderRoute: typeof DashboardPrescriptionsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/register': {
      id: '/dashboard/patients/register'
      path: '/patients/register'
      fullPath: '/dashboard/patients/register'
      preLoaderRoute: typeof DashboardPatientsRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/opd-queue': {
      id: '/dashboard/patients/opd-queue'
      path: '/patients/opd-queue'
      fullPath: '/dashboard/patients/opd-queue'
      preLoaderRoute: typeof DashboardPatientsOpdQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/$id': {
      id: '/dashboard/patients/$id'
      path: '/patients/$id'
      fullPath: '/dashboard/patients/$id'
      preLoaderRoute: typeof DashboardPatientsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dispensing/history': {
      id: '/dashboard/dispensing/history'
      path: '/dispensing/history'
      fullPath: '/dashboard/dispensing/history'
      preLoaderRoute: typeof DashboardDispensingHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dispensing/$id': {
      id: '/dashboard/dispensing/$id'
      path: '/dispensing/$id'
      fullPath: '/dashboard/dispensing/$id'
      preLoaderRoute: typeof DashboardDispensingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/schedule': {
      id: '/dashboard/appointments/schedule'
      path: '/appointments/schedule'
      fullPath: '/dashboard/appointments/schedule'
      preLoaderRoute: typeof DashboardAppointmentsScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/$id': {
      id: '/dashboard/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/dashboard/appointments/$id'
      preLoaderRoute: typeof DashboardAppointmentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/security': {
      id: '/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof DashboardAdminSecurityRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/prescriptions/templates/': {
      id: '/dashboard/prescriptions/templates/'
      path: '/prescriptions/templates'
      fullPath: '/dashboard/prescriptions/templates'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/security/': {
      id: '/dashboard/admin/security/'
      path: '/'
      fullPath: '/dashboard/admin/security/'
      preLoaderRoute: typeof DashboardAdminSecurityIndexRouteImport
      parentRoute: typeof DashboardAdminSecurityRoute
    }
    '/dashboard/prescriptions/templates/create': {
      id: '/dashboard/prescriptions/templates/create'
      path: '/prescriptions/templates/create'
      fullPath: '/dashboard/prescriptions/templates/create'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/templates/$id': {
      id: '/dashboard/prescriptions/templates/$id'
      path: '/prescriptions/templates/$id'
      fullPath: '/dashboard/prescriptions/templates/$id'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/security/keys': {
      id: '/dashboard/admin/security/keys'
      path: '/keys'
      fullPath: '/dashboard/admin/security/keys'
      preLoaderRoute: typeof DashboardAdminSecurityKeysRouteImport
      parentRoute: typeof DashboardAdminSecurityRoute
    }
    '/dashboard/admin/security/events': {
      id: '/dashboard/admin/security/events'
      path: '/events'
      fullPath: '/dashboard/admin/security/events'
      preLoaderRoute: typeof DashboardAdminSecurityEventsRouteImport
      parentRoute: typeof DashboardAdminSecurityRoute
    }
  }
}

interface DashboardAdminSecurityRouteChildren {
  DashboardAdminSecurityEventsRoute: typeof DashboardAdminSecurityEventsRoute
  DashboardAdminSecurityKeysRoute: typeof DashboardAdminSecurityKeysRoute
  DashboardAdminSecurityIndexRoute: typeof DashboardAdminSecurityIndexRoute
}

const DashboardAdminSecurityRouteChildren: DashboardAdminSecurityRouteChildren =
  {
    DashboardAdminSecurityEventsRoute: DashboardAdminSecurityEventsRoute,
    DashboardAdminSecurityKeysRoute: DashboardAdminSecurityKeysRoute,
    DashboardAdminSecurityIndexRoute: DashboardAdminSecurityIndexRoute,
  }

const DashboardAdminSecurityRouteWithChildren =
  DashboardAdminSecurityRoute._addFileChildren(
    DashboardAdminSecurityRouteChildren,
  )

interface DashboardAdminRouteChildren {
  DashboardAdminSecurityRoute: typeof DashboardAdminSecurityRouteWithChildren
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminSecurityRoute: DashboardAdminSecurityRouteWithChildren,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardSettingsRouteChildren {
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppointmentsIdRoute: typeof DashboardAppointmentsIdRoute
  DashboardAppointmentsScheduleRoute: typeof DashboardAppointmentsScheduleRoute
  DashboardDispensingIdRoute: typeof DashboardDispensingIdRoute
  DashboardDispensingHistoryRoute: typeof DashboardDispensingHistoryRoute
  DashboardPatientsIdRoute: typeof DashboardPatientsIdRoute
  DashboardPatientsOpdQueueRoute: typeof DashboardPatientsOpdQueueRoute
  DashboardPatientsRegisterRoute: typeof DashboardPatientsRegisterRoute
  DashboardPrescriptionsIdRoute: typeof DashboardPrescriptionsIdRoute
  DashboardPrescriptionsCreateRoute: typeof DashboardPrescriptionsCreateRoute
  DashboardStaffIdRoute: typeof DashboardStaffIdRoute
  DashboardStaffRolesRoute: typeof DashboardStaffRolesRoute
  DashboardVitalsIdRoute: typeof DashboardVitalsIdRoute
  DashboardVitalsHistoryRoute: typeof DashboardVitalsHistoryRoute
  DashboardVitalsRecordRoute: typeof DashboardVitalsRecordRoute
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute
  DashboardDispensingIndexRoute: typeof DashboardDispensingIndexRoute
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute
  DashboardPrescriptionsIndexRoute: typeof DashboardPrescriptionsIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardVitalsIndexRoute: typeof DashboardVitalsIndexRoute
  DashboardPrescriptionsTemplatesIdRoute: typeof DashboardPrescriptionsTemplatesIdRoute
  DashboardPrescriptionsTemplatesCreateRoute: typeof DashboardPrescriptionsTemplatesCreateRoute
  DashboardPrescriptionsTemplatesIndexRoute: typeof DashboardPrescriptionsTemplatesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppointmentsIdRoute: DashboardAppointmentsIdRoute,
  DashboardAppointmentsScheduleRoute: DashboardAppointmentsScheduleRoute,
  DashboardDispensingIdRoute: DashboardDispensingIdRoute,
  DashboardDispensingHistoryRoute: DashboardDispensingHistoryRoute,
  DashboardPatientsIdRoute: DashboardPatientsIdRoute,
  DashboardPatientsOpdQueueRoute: DashboardPatientsOpdQueueRoute,
  DashboardPatientsRegisterRoute: DashboardPatientsRegisterRoute,
  DashboardPrescriptionsIdRoute: DashboardPrescriptionsIdRoute,
  DashboardPrescriptionsCreateRoute: DashboardPrescriptionsCreateRoute,
  DashboardStaffIdRoute: DashboardStaffIdRoute,
  DashboardStaffRolesRoute: DashboardStaffRolesRoute,
  DashboardVitalsIdRoute: DashboardVitalsIdRoute,
  DashboardVitalsHistoryRoute: DashboardVitalsHistoryRoute,
  DashboardVitalsRecordRoute: DashboardVitalsRecordRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardDispensingIndexRoute: DashboardDispensingIndexRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
  DashboardPrescriptionsIndexRoute: DashboardPrescriptionsIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardVitalsIndexRoute: DashboardVitalsIndexRoute,
  DashboardPrescriptionsTemplatesIdRoute:
    DashboardPrescriptionsTemplatesIdRoute,
  DashboardPrescriptionsTemplatesCreateRoute:
    DashboardPrescriptionsTemplatesCreateRoute,
  DashboardPrescriptionsTemplatesIndexRoute:
    DashboardPrescriptionsTemplatesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterHospitalRoute: RegisterHospitalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
  VerifyHospitalRoute: VerifyHospitalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
