/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyHospitalRouteImport } from './routes/verify-hospital'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterHospitalRouteImport } from './routes/register-hospital'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff/index'
import { Route as DashboardStaffIdRouteImport } from './routes/dashboard/staff/$id'

const VerifyHospitalRoute = VerifyHospitalRouteImport.update({
  id: '/verify-hospital',
  path: '/verify-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHospitalRoute = RegisterHospitalRouteImport.update({
  id: '/register-hospital',
  path: '/register-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIdRoute = DashboardStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/'
    | '/dashboard/staff/$id'
    | '/dashboard/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard'
    | '/dashboard/staff/$id'
    | '/dashboard/staff'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/'
    | '/dashboard/staff/$id'
    | '/dashboard/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterHospitalRoute: typeof RegisterHospitalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  VerifyHospitalRoute: typeof VerifyHospitalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-hospital': {
      id: '/verify-hospital'
      path: '/verify-hospital'
      fullPath: '/verify-hospital'
      preLoaderRoute: typeof VerifyHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-hospital': {
      id: '/register-hospital'
      path: '/register-hospital'
      fullPath: '/register-hospital'
      preLoaderRoute: typeof RegisterHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/$id': {
      id: '/dashboard/staff/$id'
      path: '/staff/$id'
      fullPath: '/dashboard/staff/$id'
      preLoaderRoute: typeof DashboardStaffIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStaffIdRoute: typeof DashboardStaffIdRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStaffIdRoute: DashboardStaffIdRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterHospitalRoute: RegisterHospitalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
  VerifyHospitalRoute: VerifyHospitalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
